

spring.application.name=employee-management
spring.data.mongodb.uri=${MONGODB_URI}
spring.thymeleaf.cache=false

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=10m
spring.cache.cache-names=employees,employeeById

logging.level.org.springframework.security=INFO
logging.level.com.example.employeemanagement=DEBUG

app.admin.username=admin
app.admin.password=admin123
app.admin.email=admin@company.com